DirectoryPath: ./dist
IgnoreFiles:
  - .DS_Store
  - .gitignore
  - .htmltest.yml
  - .prettier*
  - .stylelintrc*
  - .vscode
  - astro.config.*
  - /*.md
  - /*.yml
  - shblog.*
  - node_modules
CheckInternalLinks: true
CheckExternalLinks: false
CheckScripts: true
CheckMeta: true
CheckImages: true
CheckFavicon: true
IgnoreStatusCheckCode:
  - 403 # Forbidden
  - 429 # Too Many Requests
