name: Testing

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  initialize:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v5
        with:
          version: 10
      - name: Install dependencies
        run: pnpm install

  astro-test:
    needs: initialize
    runs-on: ubuntu-latest
    steps:
      - name: Run Astro tests
        run: pnpm astro check

  broken-link-test:
    needs: initialize
    runs-on: ubuntu-latest
    steps:
      - name: Run htmltest
        uses: wjdp/htmltest-action@master
        with:
          config: .htmltest.yml
